// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: proto/izanami.proto

package izanami

import (
	fmt "fmt"
	proto "google.golang.org/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "go-micro.dev/v4/api"
	client "go-micro.dev/v4/client"
	server "go-micro.dev/v4/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for Izanami service

func NewIzanamiEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for Izanami service

type IzanamiService interface {
	Call(ctx context.Context, in *CallRequest, opts ...client.CallOption) (*CallResponse, error)
	ClientStream(ctx context.Context, opts ...client.CallOption) (Izanami_ClientStreamService, error)
	ServerStream(ctx context.Context, in *ServerStreamRequest, opts ...client.CallOption) (Izanami_ServerStreamService, error)
	BidiStream(ctx context.Context, opts ...client.CallOption) (Izanami_BidiStreamService, error)
}

type izanamiService struct {
	c    client.Client
	name string
}

func NewIzanamiService(name string, c client.Client) IzanamiService {
	return &izanamiService{
		c:    c,
		name: name,
	}
}

func (c *izanamiService) Call(ctx context.Context, in *CallRequest, opts ...client.CallOption) (*CallResponse, error) {
	req := c.c.NewRequest(c.name, "Izanami.Call", in)
	out := new(CallResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *izanamiService) ClientStream(ctx context.Context, opts ...client.CallOption) (Izanami_ClientStreamService, error) {
	req := c.c.NewRequest(c.name, "Izanami.ClientStream", &ClientStreamRequest{})
	stream, err := c.c.Stream(ctx, req, opts...)
	if err != nil {
		return nil, err
	}
	return &izanamiServiceClientStream{stream}, nil
}

type Izanami_ClientStreamService interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	CloseSend() error
	Close() error
	Send(*ClientStreamRequest) error
}

type izanamiServiceClientStream struct {
	stream client.Stream
}

func (x *izanamiServiceClientStream) CloseSend() error {
	return x.stream.CloseSend()
}

func (x *izanamiServiceClientStream) Close() error {
	return x.stream.Close()
}

func (x *izanamiServiceClientStream) Context() context.Context {
	return x.stream.Context()
}

func (x *izanamiServiceClientStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *izanamiServiceClientStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *izanamiServiceClientStream) Send(m *ClientStreamRequest) error {
	return x.stream.Send(m)
}

func (c *izanamiService) ServerStream(ctx context.Context, in *ServerStreamRequest, opts ...client.CallOption) (Izanami_ServerStreamService, error) {
	req := c.c.NewRequest(c.name, "Izanami.ServerStream", &ServerStreamRequest{})
	stream, err := c.c.Stream(ctx, req, opts...)
	if err != nil {
		return nil, err
	}
	if err := stream.Send(in); err != nil {
		return nil, err
	}
	return &izanamiServiceServerStream{stream}, nil
}

type Izanami_ServerStreamService interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	CloseSend() error
	Close() error
	Recv() (*ServerStreamResponse, error)
}

type izanamiServiceServerStream struct {
	stream client.Stream
}

func (x *izanamiServiceServerStream) CloseSend() error {
	return x.stream.CloseSend()
}

func (x *izanamiServiceServerStream) Close() error {
	return x.stream.Close()
}

func (x *izanamiServiceServerStream) Context() context.Context {
	return x.stream.Context()
}

func (x *izanamiServiceServerStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *izanamiServiceServerStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *izanamiServiceServerStream) Recv() (*ServerStreamResponse, error) {
	m := new(ServerStreamResponse)
	err := x.stream.Recv(m)
	if err != nil {
		return nil, err
	}
	return m, nil
}

func (c *izanamiService) BidiStream(ctx context.Context, opts ...client.CallOption) (Izanami_BidiStreamService, error) {
	req := c.c.NewRequest(c.name, "Izanami.BidiStream", &BidiStreamRequest{})
	stream, err := c.c.Stream(ctx, req, opts...)
	if err != nil {
		return nil, err
	}
	return &izanamiServiceBidiStream{stream}, nil
}

type Izanami_BidiStreamService interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	CloseSend() error
	Close() error
	Send(*BidiStreamRequest) error
	Recv() (*BidiStreamResponse, error)
}

type izanamiServiceBidiStream struct {
	stream client.Stream
}

func (x *izanamiServiceBidiStream) CloseSend() error {
	return x.stream.CloseSend()
}

func (x *izanamiServiceBidiStream) Close() error {
	return x.stream.Close()
}

func (x *izanamiServiceBidiStream) Context() context.Context {
	return x.stream.Context()
}

func (x *izanamiServiceBidiStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *izanamiServiceBidiStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *izanamiServiceBidiStream) Send(m *BidiStreamRequest) error {
	return x.stream.Send(m)
}

func (x *izanamiServiceBidiStream) Recv() (*BidiStreamResponse, error) {
	m := new(BidiStreamResponse)
	err := x.stream.Recv(m)
	if err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for Izanami service

type IzanamiHandler interface {
	Call(context.Context, *CallRequest, *CallResponse) error
	ClientStream(context.Context, Izanami_ClientStreamStream) error
	ServerStream(context.Context, *ServerStreamRequest, Izanami_ServerStreamStream) error
	BidiStream(context.Context, Izanami_BidiStreamStream) error
}

func RegisterIzanamiHandler(s server.Server, hdlr IzanamiHandler, opts ...server.HandlerOption) error {
	type izanami interface {
		Call(ctx context.Context, in *CallRequest, out *CallResponse) error
		ClientStream(ctx context.Context, stream server.Stream) error
		ServerStream(ctx context.Context, stream server.Stream) error
		BidiStream(ctx context.Context, stream server.Stream) error
	}
	type Izanami struct {
		izanami
	}
	h := &izanamiHandler{hdlr}
	return s.Handle(s.NewHandler(&Izanami{h}, opts...))
}

type izanamiHandler struct {
	IzanamiHandler
}

func (h *izanamiHandler) Call(ctx context.Context, in *CallRequest, out *CallResponse) error {
	return h.IzanamiHandler.Call(ctx, in, out)
}

func (h *izanamiHandler) ClientStream(ctx context.Context, stream server.Stream) error {
	return h.IzanamiHandler.ClientStream(ctx, &izanamiClientStreamStream{stream})
}

type Izanami_ClientStreamStream interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Recv() (*ClientStreamRequest, error)
}

type izanamiClientStreamStream struct {
	stream server.Stream
}

func (x *izanamiClientStreamStream) Close() error {
	return x.stream.Close()
}

func (x *izanamiClientStreamStream) Context() context.Context {
	return x.stream.Context()
}

func (x *izanamiClientStreamStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *izanamiClientStreamStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *izanamiClientStreamStream) Recv() (*ClientStreamRequest, error) {
	m := new(ClientStreamRequest)
	if err := x.stream.Recv(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (h *izanamiHandler) ServerStream(ctx context.Context, stream server.Stream) error {
	m := new(ServerStreamRequest)
	if err := stream.Recv(m); err != nil {
		return err
	}
	return h.IzanamiHandler.ServerStream(ctx, m, &izanamiServerStreamStream{stream})
}

type Izanami_ServerStreamStream interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*ServerStreamResponse) error
}

type izanamiServerStreamStream struct {
	stream server.Stream
}

func (x *izanamiServerStreamStream) Close() error {
	return x.stream.Close()
}

func (x *izanamiServerStreamStream) Context() context.Context {
	return x.stream.Context()
}

func (x *izanamiServerStreamStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *izanamiServerStreamStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *izanamiServerStreamStream) Send(m *ServerStreamResponse) error {
	return x.stream.Send(m)
}

func (h *izanamiHandler) BidiStream(ctx context.Context, stream server.Stream) error {
	return h.IzanamiHandler.BidiStream(ctx, &izanamiBidiStreamStream{stream})
}

type Izanami_BidiStreamStream interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*BidiStreamResponse) error
	Recv() (*BidiStreamRequest, error)
}

type izanamiBidiStreamStream struct {
	stream server.Stream
}

func (x *izanamiBidiStreamStream) Close() error {
	return x.stream.Close()
}

func (x *izanamiBidiStreamStream) Context() context.Context {
	return x.stream.Context()
}

func (x *izanamiBidiStreamStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *izanamiBidiStreamStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *izanamiBidiStreamStream) Send(m *BidiStreamResponse) error {
	return x.stream.Send(m)
}

func (x *izanamiBidiStreamStream) Recv() (*BidiStreamRequest, error) {
	m := new(BidiStreamRequest)
	if err := x.stream.Recv(m); err != nil {
		return nil, err
	}
	return m, nil
}
